### ISSUE TITLE
Three suggestions for firmware update

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_rpcWiFi#12]
Based on the experience posted on #11, please find three suggestions:

- Provide manual procedure with `amebad_image_tool` along the procedure relying on the Python script `ambd_flash_tool.py`.
- Ensure `ambd_flash_tool.py` checks that `amebad_image_tool` actually runs and completes the job.
- Provide a progress bar, as the process is rather slow and may take up to 2 minutes.

**Comment by Pillar1989** [comment]
@rei-vilo  Thank you for your suggestion, our current focus is still on the optimization of the core software, it would be great if someone could provide a PR based on your suggestion.
