### ISSUE TITLE
My IDE routine reported the following error

### ISSUE THREAD

**Issue by az666** [Seeed-Studio/Seeed_Arduino_rpcWiFi#13]
Arduino\libraries\Seeed_Arduino_rpcWiFi-master\src\WiFiSTA.cpp:364:20: error: 'struct tcpip_adapter_dns_info_t' has no member named 'ipv4'; did you mean 'ip'?

         tcpip_dns0.ipv4 = dns1;

                    ^~~~

                    ip

**Comment by az666** [comment]
This is an official routine. Why report this error?

**Comment by Pillar1989** [comment]
https://travis-ci.com/github/Seeed-Studio/Seeed_Arduino_rpcWiFi @az666  I don't think that there is anything wrong with our code, the CI compilation is passing.
