### ISSUE TITLE
Multiple TLS/HTTPS connection not supported?

### ISSUE THREAD

**Issue by kartben** [Seeed-Studio/Seeed_Arduino_rpcWiFi#16]
I am having issues getting the WifiClientSecure + HTTPClient to work when I already have a TLS connection established

What works:
- Application is connected to Azure IoT Hub using MQTT over TLS, and I can correctly perform a GET of an HTTP resource using HttpClient

What does not work:
- Application is connected to Azure IoT Hub using MQTT over TLS, and I **cannot** correctly perform a GET of an HTTP**S** resource using HttpClient. 

It doesn't matter if I try to set the CA cert on the Client, or to pass it to the begin() method of the HTTP client, the app hangs when doing the .GET() call. It also doesn't work if I try to issue an HTTPS GET query on the exact same server that I am already connected to using MQTTS, even if the CA Cert would be the same in that case.

I have confirmed that doing the  HTTPS query in an app where it is the only TLS connection being made works just fine (`BasicHttpsClient.ino` sample)

**Comment by haiershu** [comment]
Hello, this may be caused by the new feature we added, but we are not sure, we are still testing, expect tomorrow or the day after tomorrow will have the answer

**Comment by kartben** [comment]
Thank you @haiershu - I really appreciate your quick response! Let me know if there is anything I can do to help.

**Comment by haiershu** [comment]
Hello, we are testing on the latest version, both HTTP and HTTPS can run, maybe there is something wrong with your git address, could you please share your project code with us to help us judge the problem?

**Comment by kartben** [comment]
Hi,

The issue is not about doing both HTTP and HTTPS at the same time, it's
about being able to do HTTPS while another TLS (MQTTS in my case) session
is already established.
I will try to share some code to reproduce but in the meantime I am pretty
sure a way to reproduce is to connect to two different HTTPS websites that
have different Root CAs.

Thanks!

**Comment by RoSchmi** [comment]
Hi @kartben, I would supect that there isn't enough stack memory left to support two tls-secured streams at the same time. Perhaps it is needed to close the mqtt stream before trying to perfom an https request. Even in one of my application , were there was only one https request alone, I had to allocate some buffers from another memory segment to preserve enough stack for mbedtls.

**Comment by matsujirushi** [comment]
Any updates? @haiershu

**Comment by haiershu** [comment]
@matsujirushi Please refer to RoSchmi's answer
