### ISSUE TITLE
Release #20

### ISSUE THREAD

**Issue by jimbobbennett** [Seeed-Studio/Seeed_Arduino_rpcWiFi#21]
Thanks for merging #20.

Can it be released please to the Arduino library manager. It needs a versions bump in the library.properties file and a new tag.

**Comment by Pillar1989** [comment]
@lakshanthad  pls help this

**Comment by lakshanthad** [comment]
@jimbobbennett it's done. Please wait until Arduino Library Manager automatically fetches the update.

**Comment by jimbobbennett** [comment]
Thanks - I can now see this version in PlatformIO
