### ISSUE TITLE
Cannot connect TCP/TLS over 5GHz WiFi

### ISSUE THREAD

**Issue by vshymanskyy** [Seeed-Studio/Seeed_Arduino_rpcWiFi#24]
**To Reproduce**
1. Connect to a 5GHz hotspot 
2. Try establishing TCP or TLS connection
3. Connection is either not established or stops working immediately after some small data exchange.

**Expected behavior**
Connection is established and is kept working for adequate time (minutes, hours).

**Additional context**
Just changing Hotspot configuration to 4GHz, everything starts working as expected.

**Comment by 0hotpotman0** [comment]
Try to update the 8720 firmware, and check the board selection.   
My board is working on the 5g 

![image](https://user-images.githubusercontent.com/47217650/142830325-b476eaee-1f65-4869-b133-88de3f013330.png)

**Comment by Pillar1989** [comment]
@vshymanskyy close this issue first, If you still need to discuss it, we can reopen it.

**Comment by vshymanskyy** [comment]
Confirmed
