### ISSUE TITLE
Is there a FreeRTOS implementation of this?

### ISSUE THREAD

**Issue by cg101** [Seeed-Studio/Seeed_Arduino_rpcWiFi#26]
I'd like to use the Seeed Studio W600 module on an STM32 board with FreeRTOS. I have flashed the eRPC firmware on the RTL8720DN module. How can I call the functions on the RTL8720DN module from my STM32 board? I need to have the iot_wifi.c file to be able to communicate with the RTL8720DN module from my FreeRTOS project. I found an [iot_wifi.c](https://github.com/ambiot/amazon-freertos/blob/master/vendors/realtek/boards/amebaD/ports/wifi/iot_wifi.c) file on the [amazon-freertos](https://github.com/ambiot/amazon-freertos/) repository provided for Ameda D board. But I am assuming this does not work with the eRPC firmware. Do you provide an iot_wifi.c file which works with the eRPC firmware? How would I set it up to work with my STM32 FreeRTOS project?

**Comment by Pillar1989** [comment]
@cg101  We are so sorry, we don't have any experience with the STM32 platform. But we open source all the source code as we can. I hope this can help you port to the new platform. Sorry again, I cant help you.
https://github.com/Seeed-Studio/seeed-ambd-firmware 
https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified
