### ISSUE TITLE
Include all Seeed libraries into the Seeed URL json

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_rpcWiFi#3]
See https://github.com/Seeed-Studio/Seeed_Arduino_rpcBLE/issues/2

**Comment by LynnL4** [comment]
Sorry, we have no plans to put libraries into Arduino Libraries manger at this time.

**Comment by Pillar1989** [comment]
@rei-vilo  Your Suggestions are great, but we have too many software, if each one actively raises issues to them, this eat us a lot of time, I am considering how to automatically publish to their manager, do you have any good Suggestions?

**Comment by rei-vilo** [comment]
I understand, Seeed has so many libraries...

The tricky part when generating the `.json` file is the SHA-256 signature. 

It seems most libraries publishers have an automatic procedure, but I couldn't find one.

**Comment by rei-vilo** [comment]
Please refer to my comment at [Add spartan edge libraries to Arduino Library Manager](https://forum.seeedstudio.com/t/add-spartan-edge-libraries-to-arduino-library-manager/256047/6).
