### ISSUE TITLE
Compile error with new v1.0.0

### ISSUE THREAD

**Issue by khoih-prog** [Seeed-Studio/Seeed_Arduino_rpcWiFi#5]
There is no `Seeed_mbedtls.h` in either [ArduinoCore-samd core v1.8.1](https://github.com/Seeed-Studio/ArduinoCore-samd/releases/tag/v1.8.1), [ArduinoCore-samd master](https://github.com/Seeed-Studio/ArduinoCore-samd) and this [Seeed_Arduino_rpcWiFi Library v1.0.0](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi/releases/tag/v1.0.0)

Just introduced in v1.0.0's at [WebServer.cpp Line 31](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi/blob/master/src/WebServer.cpp#L31)

This is the compiler error message

```
/home/kh/Arduino/libraries/Seeed_Arduino_rpcWiFi-1.0.0/src/WebServer.cpp:31:10: fatal error: Seeed_mbedtls.h: No such file or directory
#include "Seeed_mbedtls.h"
```

**Comment by lakshanthad** [comment]
Hi,
Please check [here](https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls) and make sure to download and install the dev branch.

Method 1: .zip file Method
- Download as a .zip file and install
https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls/archive/dev.zip

Method 2: cli Method 
- git clone https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls.git
- git checkout dev

**Comment by khoih-prog** [comment]
That's OK now using the additional [**Seeed_Arduino_mbedtls Library**](https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls/).

But it's better to have a note and/or update the dependency in [**library.properties**](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi/blob/master/library.properties)
