### ISSUE TITLE
HTTPClient sometimes doesn't return from method HTTPClient::connected()

### ISSUE THREAD

**Issue by RoSchmi** [Seeed-Studio/Seeed_Arduino_rpcWiFi#6]
I'm working on an application which writes sensor data to azure storage tables.

https://github.com/RoSchmi/AzureDataSender_Wio_Terminal

I'm using the HTTPClient of the Seeed rpcWiFi library.
I use secure transmission with https post requests and the transmission to the Azure service works properly.
For your Information: In my code I set '_reuse' to false and in my requests I send a 'Connection close' header.
In certain time intervals I make ntp requests with code according to the sample in the Seeed Wiki to synchronize the RTC.
Sometimes (very often) esp. after successful ntp requests my program stops in the process of sending new data to the Azure storage service.
By setting breakpoints in the HTTPClient library I could find out, that the program (when the issue occures) doesn't return from the HTTPClient::connected() method.
When I comment the block of code where this method is called, my program is running flawlessly with -up to the moment- more than 100 successful requests.

/*
if(connected()) {
        if(_reuse) {
            log_d("already connected, reusing connection");
        } else {
            log_d("already connected, try reuse!");
        }
        while(_client->available() > 0) {
            _client->read();
        }
        return true;
    }
*/

I suspect that there is a problem concerning the integration of the WiFi module.

**Comment by ansonhe97** [comment]
Hi @RoSchmi 

Thanks for the feedback. Please can you provide a session of your problem sample code where we can reproduce the error in our end.

Thanks!

**Comment by RoSchmi** [comment]
Thanks for your response,
My App can be downloaded from GitHub and it should not be much work to get it running. The things to do are described in the ReadMe file.
To use the App it is needed to have an Azure Acount. On the Azure Acount you must create an Azure Storage Account which is quite easy.
When you have created the Azure Storage Account you must fill in the Account name and the key (and the WiFi credentials ) lin the file include/config_secret.h in my App.
Now the App should start, automatically create a table named AnalogTestValues2020 and transfer data every 30 seconds.
To watch the tables you can use the free tool Azure Storage Explorer from Microsoft.
If you don't have an Azure Account I could give you the credentials of my account in a not public way.
You can find the post request in the file lib/roschmi-for-azure-sdk/az_wioterminal_roschmi.cpp and start debugging from there.
Please tell me if this would be an acceptable way for you to proceed.
Best regards 
RoSchmi

**Comment by RoSchmi** [comment]
I made same more investigations:
It's the _client->available() method of WiFiClientSecure that often doesn't return when a successful ntp request was made before.

**Comment by ansonhe97** [comment]
Hi @RoSchmi 

Thanks for the information and we will look into this for more debugging.

**Comment by ansonhe97** [comment]
Hi @RoSchmi 

Sounds good!

We were printing out more of the bottom layer debugging message and found bugs(not entirely sure where you called), and also didnt localised.

Best Regards,
Anson He

**Comment by RoSchmi** [comment]
Thanks
