### ISSUE TITLE
rpcWiFi library multiple definition

### ISSUE THREAD

**Issue by Kabron287** [Seeed-Studio/Seeed_Arduino_rpcWiFi#7]
`#include “rpcWiFi.h”

void setup()
{
Serial.begin(115200);
while (!Serial); // Wait to open Serial Monitor
Serial.println("Starting...");
Serial.printf(“RTL8720 Firmware Version: %s”, rpc_system_version());

}

void loop()
{
}`

Produced a lot linker errors:

`atu_netdb.c.o: In function dns_gethostbyname
atu_netdb.c:14: multiple definition of dns_gethostbyname
dns.c.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\lwip\dns.c:38: first defined here

atu_sockets.c.o: In function atu_htons
atu_sockets.c:602: multiple definition of atu_htons
sockets.c.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\lwip\sockets.c:303: first defined here

atu_sockets.c.o: In function atu_htonl
atu_sockets.c:611: multiple definition of atu_htonl
sockets.c.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\lwip\sockets.c:314: first defined here

esp_hal_log.c.o: In function pathToFileName
esp_hal_log.c:10: multiple definition of pathToFileName
esp_hal_log.c.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\esp\esp_hal_log.c:10: first defined here

esp_hal_log.c.o: In function dump_tasks
esp_hal_log.c:24: multiple definition of dump_tasks
esp_hal_log.c.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\esp\esp_hal_log.c:24: first defined here

esp_hal_log.c.o: In function ntp_conf_time
esp_hal_log.c:32: multiple definition of ntp_conf_time
esp_hal_log.c.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\esp\esp_hal_log.c:70: first defined here

mdns.c.o: In function mdns_init
mdns.c:34: multiple definition of mdns_init
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:34: first defined here

mdns.c.o: In function mdns_free
mdns.c:42: multiple definition of mdns_free
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:43: first defined here

mdns.c.o: In function mdns_hostname_set
mdns.c:54: multiple definition of mdns_hostname_set
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:50: first defined here

mdns.c.o: In function mdns_instance_name_set
mdns.c:89: multiple definition of mdns_instance_name_set
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:59: first defined here

mdns.c.o: In function mdns_service_add
mdns.c:106: multiple definition of mdns_service_add
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:67: first defined here

mdns.c.o: In function mdns_service_remove
mdns.c:136: multiple definition of mdns_service_remove
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:89: first defined here

mdns.c.o: In function mdns_service_instance_name_set
mdns.c:156: multiple definition of mdns_service_instance_name_set
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:105: first defined here

mdns.c.o: In function mdns_service_txt_item_set
mdns.c:179: multiple definition of mdns_service_txt_item_set
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:97: first defined here

mdns.c.o: In function mdns_query_results_free
mdns.c:190: multiple definition of mdns_query_results_free
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:113: first defined here

mdns.c.o: In function mdns_query_ptr
mdns.c:214: multiple definition of mdns_query_ptr
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:147: first defined here

mdns.c.o: In function mdns_query_a
mdns.c:235: multiple definition of mdns_query_a
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:255: first defined here

mdns.c.o: In function mdns_handle_system_event
mdns.c*: (.text.mdns_handle_system_event+0x0): multiple definition of mdns_handle_system_event
rpc_wifi_mdns.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_mdns.cpp:275: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_init
tcpip_adapter.c:50: multiple definition of tcpip_adapter_init
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:592: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_get_ip_info
tcpip_adapter.c:64: multiple definition of tcpip_adapter_get_ip_info
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:663: first defined here

Error linking for board Seeeduino Wio Terminal

Build failed for project ‘Test’
tcpip_adapter.c.o: In function tcpip_adapter_set_ip_info
tcpip_adapter.c:97: multiple definition of tcpip_adapter_set_ip_info
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:690: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_create_ip6_linklocal
tcpip_adapter.c:133: multiple definition of tcpip_adapter_create_ip6_linklocal
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:845: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_get_ip6_linklocal
tcpip_adapter.c:152: multiple definition of tcpip_adapter_get_ip6_linklocal
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:853: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_dhcps_option
tcpip_adapter.c:174: multiple definition of tcpip_adapter_dhcps_option
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:834: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_dhcps_start
tcpip_adapter.c:192: multiple definition of tcpip_adapter_dhcps_start
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:789: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_dhcps_stop
tcpip_adapter.c:218: multiple definition of tcpip_adapter_dhcps_stop
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:795: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_dhcpc_start
tcpip_adapter.c:239: multiple definition of tcpip_adapter_dhcpc_start
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:801: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_dhcpc_stop
tcpip_adapter.c:265: multiple definition of tcpip_adapter_dhcpc_stop
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:807: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_set_hostname
tcpip_adapter.c*: (.text.tcpip_adapter_set_hostname+0x0): multiple definition of tcpip_adapter_set_hostname
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:813: first defined here

tcpip_adapter.c.o: In function tcpip_adapter_get_hostname
tcpip_adapter.c*: (.text.tcpip_adapter_get_hostname+0x0): multiple definition of tcpip_adapter_get_hostname
rpc_wifi_api_hal.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\rtl_wifi\rpc_wifi_api_hal.cpp:822: first defined here

esp_ll_arduino.cpp.o: In function _wrap_body()
esp_ll_arduino.cpp:306: multiple definition of _wrap_body()
erpc_Unified_init.cpp.o: D:\Arduino\Proj\libraries\Seeed_Arduino_rpcUnified\src\erpc_Unified_init.cpp:139: first defined here

collect2.exe*: error: ld returned 1 exit status`

**Comment by Kabron287** [comment]
I guess it was a conflict with **Seeed_Arduino_atUnified-1.0.0** library.
But now, I get:
 ResolveLibrary(esp_system.h)eed_Arduino_mbedtls-2.0.0\src\port\esp_hardware.c:11:10: fatal error: esp_system.h: No such file or directory

  -> candidates: []
 #include <esp_system.h>
Though **esp_system.h** does present in **Seeed_Arduino_rpcUnified**

**Comment by Pillar1989** [comment]
@Kabron287  Previously AT is estimated to be deprecated, please use the software of RPC. Can I ask whether this issue can be closed?

**Comment by Kabron287** [comment]
Well, I reached successful compilation and reflash rtl8270 with eRPC FW.
But when I dowload above sketch to Wio Terminal I saw only **Starting...** on Serial Terminal.
And nothing more.

**Comment by lakshanthad** [comment]
Hi @Kabron287. 
Could you reinstall the necessary libraries for Wi-Fi at first? Recently we have updated the libraries.
Follow [here](https://wiki.seeedstudio.com/Wio-Terminal-Network-Overview/#libraries-installations-erpc)

Also make sure you have flashed the RTL87290 Firmware version 2.0.3
Follow [here](https://github.com/Seeed-Studio/seeed-ambd-firmware/releases)

Let me know how it goes

**Comment by Kabron287** [comment]
Well, after several attempts it works!
Thanks a lot.
