### ISSUE TITLE
Include all the Wio Terminal related libraries into the Seeed URL json

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_rpcWiFi#8]
This is the continuation of #3.

A doable solution would be to group all the libraries related to a specific board together and release the corresponding JSON file. 

For example, the libraries related to the Wio Terminal include

* [Seeed_Arduino_rpcWiFi ](https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi) - master branch
* [Seeed_Arduino_rpcUnified ](https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified) - master branch
* [Seeed_Arduino_mbedtls ](https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls/tree/dev) - dev branch
* [Seeed_Arduino_FS ](https://github.com/Seeed-Studio/Seeed_Arduino_FS/tree/master) - master branch
* [Seeed_Arduino_SFUD ](https://github.com/Seeed-Studio/Seeed_Arduino_SFUD) - master branch
* [Seeed_Arduino_rpcBLE](https://github.com/Seeed-Studio/Seeed_Arduino_rpcBLE)
* [Seeed_Arduino_LCD](https://github.com/Seeed-Studio/Seeed_Arduino_LCD)
* [Seeed_Arduino_Audio](https://github.com/Seeed-Studio/Seeed_Arduino_Audio)
* [Seeed_Arduino_LIS3DHTR](https://github.com/Seeed-Studio/Seeed_Arduino_LIS3DHTR/tree/master)
* [Seeed_Arduino_RTC](https://github.com/Seeed-Studio/Seeed_Arduino_RTC)
* [USB Host Library SAMD](https://github.com/gdsports/USB_Host_Library_SAMD)
* [Adafruit TinyUSB Library for Arduino](https://github.com/adafruit/Adafruit_TinyUSB_Arduino)
* [SparkFun_BQ27441_Arduino_Library](https://github.com/sparkfun/SparkFun_BQ27441_Arduino_Library)

**Comment by rei-vilo** [comment]
Please refer to this [post](https://forum.seeedstudio.com/t/add-spartan-edge-libraries-to-arduino-library-manager/256047/9?u=reivilo).

**Comment by Pillar1989** [comment]
@rei-vilo  Thanks for the suggestion, @lakshanthad  already did.
https://github.com/arduino/Arduino/issues/11113
