### ISSUE TITLE
WiFiClientSecure function connected() doesn't return with false after function stop() was called.

### ISSUE THREAD

**Issue by RoSchmi** [Seeed-Studio/Seeed_Arduino_rpcWiFi#9]
I made some tests with the httpClient of Seeed_Arduino_rpcWiFi library. My App which is loading sensor data with https 
transmission to Azure Storage Tables (https://github.com/RoSchmi/AzureDataSender_Wio_Terminal) is running fine now for 
many successful uploads (unfortunately yet not endlessly) when I'm using the right root certificate. 
To test what happens if I would use a corrupted root certificate I changed some characters in the root certificate 
and saw an unexpected behavior.
On the first try to upload I saw that my Post request (in: lib/roschmi-for-azure-sdk/az_wioterminal_roschmi.cpp) returned with -2 (HTTPC_ERROR_SEND_HEADER_FAILED) 
and in WiFIClientSecure the function stop() was called. 
On the next Post request the WiFiClientSecure::connected() function (falsely!?) returns with true, no secure transPortTrait is created, the  HTTPClient::sendHeader command never returns and the program hangs.

To fix the issue I added a '_connected = false;' command in WiFiClientSecure:

    void WiFiClientSecure::stop()
    {
        if (_socket >= 0)
        {
            close(_socket);
            _socket = -1;
            _connected = false;
        }
        if (sslclient != NULL)
        {
            stop_ssl_socket(sslclient, _CA_cert, _cert, _private_key);
            ssl_client_destroy(sslclient);
            _rxBuffer.reset();
            _rxBuffer = NULL;
            sslclient = NULL;
            //RoSchmi added
            _connected = false;
        }
    }

With this change it works but I'm not sure if this fix is enough to solve the problem or if I'm doing something wrong

**Comment by LynnL4** [comment]
This is really strange, because _connected will not be set to true if the connection is not established properly. https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi/blob/ e5dbe5ec3927a00b7a477dbce3ea06ddbe56d004/src/WiFiClientSecure.cpp#L282

**Comment by RoSchmi** [comment]
When I'm debugging the code with now the latest firmware v2.1.0 and the latest rpcWifI Lib I can see that _connected is set to true even if the certificate is corrupted. May be that _connected means that an unsecure connection is established. Whatever the reason for the issue may be, with a corrupted certificate the application crashes in the second try to transmit data.

**Comment by RoSchmi** [comment]
Still the same with RTL8720 firmware v2.1.1
